## Heartbeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/heartbeat.docker.yml
#

heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls: ["<http://localhost:9200>"]
  username: elastic
  password: ${ELASTIC_PASSWORD}
  id: service-status 
  name: Service Status
  service.name: my-apm-service-name
  hosts: ["<http://localhost:9200>"]
  check.response.status: [200]
  enabled: true
  ipv4: true
  ipv6: true
  mode: any

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
  ipv4: true
  ipv6: true
  mode: any

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["<http://localhost:9200>"]
  username: elastic
  password: ${ELASTIC_PASSWORD}

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/heartbeat/current/http-endpoint.html
#

http.enabled: true
http.host: 0.0.0.0
setup.kibana: 
  host: ["<http://localhost:5601>"]
